version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: rickgeersing_postgres
    restart: always
    environment:
      - POSTGRES_USER=rickgeersing
      - POSTGRES_PASSWORD=my-secret-password
      - POSTGRES_DB=rickgeersing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
